# Generated by Django 5.2.4 on 2025-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('chat_time', models.CharField(max_length=45)),
                ('chat_name', models.CharField(max_length=45)),
                ('chat_str', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('les_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('les_name', models.CharField(max_length=30)),
                ('les_str', models.CharField(max_length=300)),
                ('les_score', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_gender', models.CharField(max_length=20)),
                ('stu_mbti', models.CharField(max_length=20)),
                ('stu_email', models.CharField(max_length=40)),
                ('stu_pwd', models.CharField(max_length=20)),
                ('stu_area', models.CharField(max_length=20)),
                ('stu_style', models.CharField(max_length=20)),
                ('stu_score', models.CharField(max_length=20)),
                ('stu_tag', models.CharField(max_length=1)),
            ],
        ),
    ]
