# Generated by Django 5.2.4 on 2025-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_likerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Love',
            fields=[
                ('love_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('love_a', models.CharField(max_length=30)),
                ('love_b', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('mes_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mes_a', models.CharField(max_length=30)),
                ('mes_b', models.CharField(max_length=30)),
                ('mes_str', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='LikeRecord',
        ),
    ]
