# Generated by Django 5.2.4 on 2025-07-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_love_mes_delete_likerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_tag',
            field=models.CharField(max_length=40),
        ),
    ]
