# Generated by Django 5.2.4 on 2025-07-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_studentinfo_stu_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_v', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_tag',
            field=models.CharField(max_length=1),
        ),
    ]
