# Generated by Django 5.2.4 on 2025-07-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
