# Generated by Django 5.2.4 on 2025-07-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_card_delete_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mes',
        ),
    ]
