# Generated by Django 5.2.4 on 2025-07-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
