# Generated by Django 5.2.4 on 2025-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=20)),
                ('card_date', models.CharField(max_length=30)),
            ],
        ),
    ]
