# Generated by Django 5.2.4 on 2025-07-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_score',
            field=models.IntegerField(),
        ),
    ]
